name: Security Scan

on: [push, pull_request]

jobs:
  security_scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit
        run: |
          if [ -f pyproject.toml ]; then
            bandit -r ./ -c pyproject.toml -f json -o bandit-results.json
          else
            bandit -r ./ -f json -o bandit-results.json
          fi

      - name: Upload Results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: bandit-results.json
